//HintName: StrongTypeAttributes.g.cs
// <auto-generated />
#nullable enable

namespace SuperStrong.Types
{
    [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class StrongTypeAttribute<TPrimitive> : global::System.Attribute
        where TPrimitive : notnull;

    [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    internal sealed class StrongTypeAttribute<TPrimitive, TTemplate> : global::System.Attribute
        where TPrimitive : notnull
        where TTemplate : notnull, global::SuperStrong.Types.IStrongTypeTemplate<TPrimitive>;
}