using System.Text;

namespace SuperStrong.Types.Generators;

internal static class SourceBuilder
{
    public static string Build(StrongTypeModel model)
    {
        var writer = new IndentedWriter(new StringBuilder());

        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using SuperStrong.Types;");
        writer.Line();

        IDisposable? namespaceScope = null;

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            namespaceScope = writer.Block($"namespace {model.Namespace}");
        }

        var ancestorScopes = new Stack<IDisposable>();

        foreach (var ancestor in model.AncestorTypeNames)
        {
            ancestorScopes.Push(writer.Block($"partial class {ancestor}"));
        }

        using (writer.Block($"partial class {model.TypeName} : IStrongType<{model.TypeName}, {model.PrimitiveType}>"))
        {
            writer.Line($"private readonly {model.PrimitiveType} _value;");
            writer.Line();

            using (writer.Block($"private {model.TypeName}({model.PrimitiveType} value)"))
            {
                writer.Line("_value = value;");
            }
            writer.Line();

            using (writer.Block($"public static {model.TypeName} Create({model.PrimitiveType} value)"))
            {
                writer.Line("StrongType.EnsureValid(value, Definition);");
                writer.Line();
                writer.Line($"return new {model.TypeName}(value);");
            }
            writer.Line();

            writer.Line($"public {model.PrimitiveType} AsPrimitive() => _value;");
            writer.Line();

            writer.Line("public override int GetHashCode() => _value.GetHashCode();");
            writer.Line();

            writer.Line($"public override bool Equals(object? obj) => obj is {model.TypeName} other && _value.Equals(other._value);");
        }

        while (ancestorScopes.Count > 0)
        {
            ancestorScopes.Pop().Dispose();
        }

        namespaceScope?.Dispose();

        return writer.ToString();
    }
}
