using SuperStrong.Types.Generators.FeatureEmitters;
using SuperStrong.Types.Generators.Helpers;
using System.Collections.Immutable;
using System.Text;

namespace SuperStrong.Types.Generators;

internal static class SourceBuilder
{
    public static string Build(StrongTypeModel model, ImmutableArray<IStrongTypeFeatureEmitter> features)
    {
        var writer = new IndentedWriter(new StringBuilder());

        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line();

        IDisposable? namespaceScope = null;

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            namespaceScope = writer.Block($"namespace {model.Namespace}");
        }

        var ancestorScopes = new Stack<IDisposable>();

        foreach (var ancestor in model.AncestorTypeNames)
        {
            ancestorScopes.Push(writer.Block($"partial class {ancestor}"));
        }

        for (var i = 0; i < features.Length; i++)
        {
            features[i].Emit(writer, model);

            if (i < features.Length - 1)
            {
                writer.Line();
            }
        }

        while (ancestorScopes.Count > 0)
        {
            ancestorScopes.Pop().Dispose();
        }

        namespaceScope?.Dispose();

        return writer.ToString();
    }
}
