//HintName: Sample_UserId.g.cs
// <auto-generated />
#nullable enable

namespace Sample
{
    partial class UserId
    {
        private readonly int _value;

        private UserId(int value)
        {
            _value = value;
        }
    }

    partial class UserId : global::SuperStrong.Types.IHasStrongTypeDefinition<int>
    {
        public static global::SuperStrong.Types.StrongTypeDefinition<int> Definition => global::SuperStrong.Types.StrongType.Define<int>();

        static global::SuperStrong.Types.StrongTypeDefinition<int> global::SuperStrong.Types.IHasStrongTypeDefinition<int>.Definition => Definition;
    }

    partial class UserId : global::SuperStrong.Types.IStrongType<UserId, int>
    {
        public static UserId Create(int value)
        {
            global::SuperStrong.Types.StrongType.EnsureValid(value, Definition);

            return new UserId(value);
        }

        public int AsPrimitive() => _value;
    }

    partial class UserId
    {
        public override int GetHashCode() => _value.GetHashCode();

        public override bool Equals(object? obj) => obj is UserId other && _value.Equals(other._value);
    }

    partial class UserId
    {
        public override string ToString() => _value.ToString();
    }

}
