//HintName: Sample_Container_TestStrongType.g.cs
// <auto-generated />
#nullable enable

namespace Sample
{
    partial struct Container
    {
        partial class TestStrongType : global::SuperStrong.Types.IStrongType<TestStrongType, int>
        {
            private readonly int _value;

            private TestStrongType(int value)
            {
                _value = value;
            }

            public static TestStrongType Create(int value)
            {
                global::SuperStrong.Types.StrongType.EnsureValid(value, Definition);

                return new TestStrongType(value);
            }

            public static bool TryCreate(int value, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
            {
                if (global::SuperStrong.Types.StrongType.IsValid(value, Definition))
                {
                    result = new TestStrongType(value);
                    return true;
                }

                result = null;
                return false;
            }

            public int AsPrimitive() => _value;

            int global::SuperStrong.Types.IStrongType<TestStrongType, int>.AsPrimitive()
            {
                return AsPrimitive();
            }
        }

        partial class TestStrongType : global::SuperStrong.Types.IHasStrongTypeDefinition<int>
        {
            public static global::SuperStrong.Types.StrongTypeDefinition<int> Definition { get; } = global::SuperStrong.Types.StrongType.Define<int>();

            static global::SuperStrong.Types.StrongTypeDefinition<int> global::SuperStrong.Types.IHasStrongTypeDefinition<int>.Definition => Definition;
        }

        partial class TestStrongType : global::System.IEquatable<TestStrongType>, global::System.Numerics.IEqualityOperators<TestStrongType, TestStrongType, bool>
        {
            public bool Equals(TestStrongType? other) => other is not null && _value.Equals(other._value);

            bool global::System.IEquatable<TestStrongType>.Equals(TestStrongType? other)
            {
                return Equals(other);
            }

            public override bool Equals(object? obj) => obj is TestStrongType other && Equals(other);

            public override int GetHashCode() => _value.GetHashCode();

            public static bool operator ==(TestStrongType? left, TestStrongType? right)
            {
                if (left is null)
                {
                    return right is null;
                }

                return left.Equals(right);
            }

            public static bool operator !=(TestStrongType? left, TestStrongType? right) => !(left == right);
        }

        partial class TestStrongType
        {
            public override string ToString() => _value.ToString();
        }

    }
}
