//HintName: Sample_TestStrongType.g.cs
// <auto-generated />
#nullable enable

namespace Sample
{
    partial class TestStrongType : global::SuperStrong.Types.IStrongType<TestStrongType, global::System.DateTimeOffset>
    {
        private readonly global::System.DateTimeOffset _value;

        private TestStrongType(global::System.DateTimeOffset value)
        {
            _value = value;
        }

        public static TestStrongType Create(global::System.DateTimeOffset value)
        {
            global::SuperStrong.Types.StrongType.EnsureValid(value, Definition);

            return new TestStrongType(value);
        }

        public static bool TryCreate(global::System.DateTimeOffset value, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            if (global::SuperStrong.Types.StrongType.IsValid(value, Definition))
            {
                result = new TestStrongType(value);
                return true;
            }

            result = null;
            return false;
        }

        public global::System.DateTimeOffset AsPrimitive() => _value;

        global::System.DateTimeOffset global::SuperStrong.Types.IStrongType<TestStrongType, global::System.DateTimeOffset>.AsPrimitive()
        {
            return AsPrimitive();
        }
    }

    partial class TestStrongType : global::SuperStrong.Types.IHasStrongTypeDefinition<global::System.DateTimeOffset>
    {
        public static global::SuperStrong.Types.StrongTypeDefinition<global::System.DateTimeOffset> Definition { get; } = global::SuperStrong.Types.StrongType.Define<global::System.DateTimeOffset>();

        static global::SuperStrong.Types.StrongTypeDefinition<global::System.DateTimeOffset> global::SuperStrong.Types.IHasStrongTypeDefinition<global::System.DateTimeOffset>.Definition => Definition;
    }

    partial class TestStrongType : global::System.IEquatable<TestStrongType>, global::System.Numerics.IEqualityOperators<TestStrongType, TestStrongType, bool>
    {
        public bool Equals(TestStrongType? other) => other is not null && _value.Equals(other._value);

        bool global::System.IEquatable<TestStrongType>.Equals(TestStrongType? other)
        {
            return Equals(other);
        }

        public override bool Equals(object? obj) => obj is TestStrongType other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(TestStrongType? left, TestStrongType? right)
        {
            if (left is null)
            {
                return right is null;
            }

            return left.Equals(right);
        }

        public static bool operator !=(TestStrongType? left, TestStrongType? right) => !(left == right);
    }

    partial class TestStrongType
    {
        public override string ToString() => _value.ToString();
    }

    partial class TestStrongType : global::System.IParsable<TestStrongType>
    {
        public static TestStrongType Parse(string s, global::System.IFormatProvider? provider)
        {
            return Create(InvokeParse<global::System.DateTimeOffset>(s, provider));

            static T InvokeParse<T>(string s, global::System.IFormatProvider? provider) where T : global::System.IParsable<T>
            {
                return T.Parse(s, provider);
            }
        }

        public static bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            if (InvokeTryParse<global::System.DateTimeOffset>(s, provider, out var primitive))
            {
                return TryCreate(primitive, out result);
            }

            result = null;
            return false;

            static bool InvokeTryParse<T>(string? s, global::System.IFormatProvider? provider, out T result) where T : global::System.IParsable<T>
            {
                return T.TryParse(s, provider, out result!);
            }
        }
    }

    partial class TestStrongType : global::System.ISpanParsable<TestStrongType>
    {
        public static TestStrongType Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider)
        {
            return Create(InvokeParse<global::System.DateTimeOffset>(s, provider));

            static T InvokeParse<T>(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider) where T : global::System.ISpanParsable<T>
            {
                return T.Parse(s, provider);
            }
        }

        public static bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            if (InvokeTryParse<global::System.DateTimeOffset>(s, provider, out var primitive))
            {
                return TryCreate(primitive, out result);
            }

            result = null;
            return false;

            static bool InvokeTryParse<T>(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out T result) where T : global::System.ISpanParsable<T>
            {
                return T.TryParse(s, provider, out result!);
            }
        }
    }

    partial class TestStrongType : global::System.IFormattable
    {
        public string ToString(string? format, global::System.IFormatProvider? formatProvider)
        {
            return InvokeToString<global::System.DateTimeOffset>(_value, format, formatProvider);

            static string InvokeToString<T>(T value, string? format, global::System.IFormatProvider? formatProvider) where T : global::System.IFormattable
            {
                return value.ToString(format, formatProvider);
            }
        }

        string global::System.IFormattable.ToString(string? format, global::System.IFormatProvider? formatProvider)
        {
            return ToString(format, formatProvider);
        }
    }

    partial class TestStrongType : global::System.ISpanFormattable
    {
        public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)
        {
            return InvokeTryFormat<global::System.DateTimeOffset>(_value, destination, out charsWritten, format, provider);

            static bool InvokeTryFormat<T>(T value, global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider) where T : global::System.ISpanFormattable
            {
                return value.TryFormat(destination, out charsWritten, format, provider);
            }
        }

        bool global::System.ISpanFormattable.TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)
        {
            return TryFormat(destination, out charsWritten, format, provider);
        }
    }

    partial class TestStrongType : global::System.IUtf8SpanFormattable
    {
        public bool TryFormat(global::System.Span<byte> utf8Destination, out int bytesWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)
        {
            return InvokeTryFormat<global::System.DateTimeOffset>(_value, utf8Destination, out bytesWritten, format, provider);

            static bool InvokeTryFormat<T>(T value, global::System.Span<byte> utf8Destination, out int bytesWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider) where T : global::System.IUtf8SpanFormattable
            {
                return value.TryFormat(utf8Destination, out bytesWritten, format, provider);
            }
        }

        bool global::System.IUtf8SpanFormattable.TryFormat(global::System.Span<byte> utf8Destination, out int bytesWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)
        {
            return TryFormat(utf8Destination, out bytesWritten, format, provider);
        }
    }

    partial class TestStrongType : global::System.IComparable<TestStrongType>
    {
        public int CompareTo(TestStrongType? other)
        {
            if (other is null)
            {
                return 1;
            }

            return InvokeCompareTo<global::System.DateTimeOffset>(_value, other._value);

            static int InvokeCompareTo<T>(T value, T other) where T : global::System.IComparable<T>
            {
                return value.CompareTo(other);
            }
        }
    }

}
