//HintName: Sample_TestStrongType.g.cs
// <auto-generated />
#nullable enable

namespace Sample
{
    [global::System.Diagnostics.DebuggerDisplayAttribute("{_value}")]
    [global::System.ComponentModel.TypeConverterAttribute(typeof(global::SuperStrong.Types.Converters.StrongTypeConverter<TestStrongType, long>))]
    [global::System.Text.Json.Serialization.JsonConverterAttribute(typeof(global::SuperStrong.Types.Converters.JsonStrongTypeConverter<TestStrongType, long>))]
    partial class TestStrongType : global::SuperStrong.Types.IStrongType<TestStrongType, long>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        private readonly long _value;

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        private TestStrongType(long value)
        {
            _value = value;
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static TestStrongType From(long value)
        {
            global::SuperStrong.Types.StrongType.EnsureValid(value, Definition);

            return new TestStrongType(value);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static TestStrongType global::SuperStrong.Types.IStrongType<TestStrongType, long>.From(long value)
        {
            return From(value);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static bool TryFrom(long value, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            if (global::SuperStrong.Types.StrongType.IsValid(value, Definition))
            {
                result = new TestStrongType(value);
                return true;
            }

            result = null;
            return false;
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static bool global::SuperStrong.Types.IStrongType<TestStrongType, long>.TryFrom(long value, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            return TryFrom(value, out result);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public long AsPrimitive() => _value;

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        long global::SuperStrong.Types.IStrongType<TestStrongType, long>.AsPrimitive()
        {
            return AsPrimitive();
        }
    }

    partial class TestStrongType
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static global::SuperStrong.Types.StrongTypeDefinition<long> Definition { get; } = global::SuperStrong.Types.StrongType.Define<long>();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static global::SuperStrong.Types.StrongTypeDefinition<long> global::SuperStrong.Types.IStrongType<TestStrongType, long>.Definition => Definition;
    }

    partial class TestStrongType : global::System.IEquatable<TestStrongType>, global::System.Numerics.IEqualityOperators<TestStrongType, TestStrongType, bool>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public bool Equals(TestStrongType? other) => other is not null && _value.Equals(other._value);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        bool global::System.IEquatable<TestStrongType>.Equals(TestStrongType? other)
        {
            return Equals(other);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static bool operator ==(TestStrongType? left, TestStrongType? right)
        {
            if (left is null)
            {
                return right is null;
            }

            return left.Equals(right);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static bool global::System.Numerics.IEqualityOperators<TestStrongType, TestStrongType, bool>.operator ==(TestStrongType? left, TestStrongType? right)
        {
            return left == right;
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static bool operator !=(TestStrongType? left, TestStrongType? right) => !(left == right);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static bool global::System.Numerics.IEqualityOperators<TestStrongType, TestStrongType, bool>.operator !=(TestStrongType? left, TestStrongType? right)
        {
            return left != right;
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public override bool Equals(object? obj) => obj is TestStrongType other && Equals(other);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public override int GetHashCode() => _value.GetHashCode();
    }

    partial class TestStrongType
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public override string ToString() => _value.ToString();
    }

    partial class TestStrongType : global::System.IParsable<TestStrongType>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static TestStrongType Parse(string s, global::System.IFormatProvider? provider)
        {
            return From(InvokeParse<long>(s, provider));

            static T InvokeParse<T>(string s, global::System.IFormatProvider? provider) where T : global::System.IParsable<T>
            {
                return T.Parse(s, provider);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static TestStrongType global::System.IParsable<TestStrongType>.Parse(string s, global::System.IFormatProvider? provider)
        {
            return Parse(s, provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            if (InvokeTryParse<long>(s, provider, out var primitive))
            {
                return TryFrom(primitive, out result);
            }

            result = null;
            return false;

            static bool InvokeTryParse<T>(string? s, global::System.IFormatProvider? provider, out T result) where T : global::System.IParsable<T>
            {
                return T.TryParse(s, provider, out result!);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static bool global::System.IParsable<TestStrongType>.TryParse(string? s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            return TryParse(s, provider, out result);
        }
    }

    partial class TestStrongType : global::System.ISpanParsable<TestStrongType>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static TestStrongType Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider)
        {
            return From(InvokeParse<long>(s, provider));

            static T InvokeParse<T>(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider) where T : global::System.ISpanParsable<T>
            {
                return T.Parse(s, provider);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static TestStrongType global::System.ISpanParsable<TestStrongType>.Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider)
        {
            return Parse(s, provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            if (InvokeTryParse<long>(s, provider, out var primitive))
            {
                return TryFrom(primitive, out result);
            }

            result = null;
            return false;

            static bool InvokeTryParse<T>(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out T result) where T : global::System.ISpanParsable<T>
            {
                return T.TryParse(s, provider, out result!);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static bool global::System.ISpanParsable<TestStrongType>.TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            return TryParse(s, provider, out result);
        }
    }

    partial class TestStrongType : global::System.IUtf8SpanParsable<TestStrongType>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static TestStrongType Parse(global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider)
        {
            return From(InvokeParse<long>(utf8Text, provider));

            static T InvokeParse<T>(global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider) where T : global::System.IUtf8SpanParsable<T>
            {
                return T.Parse(utf8Text, provider);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static TestStrongType global::System.IUtf8SpanParsable<TestStrongType>.Parse(global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider)
        {
            return Parse(utf8Text, provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public static bool TryParse(global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            if (InvokeTryParse<long>(utf8Text, provider, out var primitive))
            {
                return TryFrom(primitive, out result);
            }

            result = null;
            return false;

            static bool InvokeTryParse<T>(global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider, out T result) where T : global::System.IUtf8SpanParsable<T>
            {
                return T.TryParse(utf8Text, provider, out result!);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        static bool global::System.IUtf8SpanParsable<TestStrongType>.TryParse(global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            return TryParse(utf8Text, provider, out result);
        }
    }

    partial class TestStrongType : global::System.IFormattable
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public string ToString(string? format, global::System.IFormatProvider? formatProvider)
        {
            return InvokeToString<long>(_value, format, formatProvider);

            static string InvokeToString<T>(T value, string? format, global::System.IFormatProvider? formatProvider) where T : global::System.IFormattable
            {
                return value.ToString(format, formatProvider);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        string global::System.IFormattable.ToString(string? format, global::System.IFormatProvider? formatProvider)
        {
            return ToString(format, formatProvider);
        }
    }

    partial class TestStrongType : global::System.ISpanFormattable
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)
        {
            return InvokeTryFormat<long>(_value, destination, out charsWritten, format, provider);

            static bool InvokeTryFormat<T>(T value, global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider) where T : global::System.ISpanFormattable
            {
                return value.TryFormat(destination, out charsWritten, format, provider);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        bool global::System.ISpanFormattable.TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)
        {
            return TryFormat(destination, out charsWritten, format, provider);
        }
    }

    partial class TestStrongType : global::System.IUtf8SpanFormattable
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public bool TryFormat(global::System.Span<byte> utf8Destination, out int bytesWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)
        {
            return InvokeTryFormat<long>(_value, utf8Destination, out bytesWritten, format, provider);

            static bool InvokeTryFormat<T>(T value, global::System.Span<byte> utf8Destination, out int bytesWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider) where T : global::System.IUtf8SpanFormattable
            {
                return value.TryFormat(utf8Destination, out bytesWritten, format, provider);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        bool global::System.IUtf8SpanFormattable.TryFormat(global::System.Span<byte> utf8Destination, out int bytesWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)
        {
            return TryFormat(utf8Destination, out bytesWritten, format, provider);
        }
    }

    partial class TestStrongType : global::System.IComparable<TestStrongType>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        public int CompareTo(TestStrongType? other)
        {
            if (other is null)
            {
                return 1;
            }

            return InvokeCompareTo<long>(_value, other._value);

            static int InvokeCompareTo<T>(T value, T other) where T : global::System.IComparable<T>
            {
                return value.CompareTo(other);
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        int global::System.IComparable<TestStrongType>.CompareTo(TestStrongType? other)
        {
            return CompareTo(other);
        }
    }

    partial class TestStrongType : global::System.IConvertible
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        global::System.TypeCode global::System.IConvertible.GetTypeCode()
        {
            return ((global::System.IConvertible)_value).GetTypeCode();
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        bool global::System.IConvertible.ToBoolean(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToBoolean(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        byte global::System.IConvertible.ToByte(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToByte(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        char global::System.IConvertible.ToChar(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToChar(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        global::System.DateTime global::System.IConvertible.ToDateTime(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToDateTime(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        decimal global::System.IConvertible.ToDecimal(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToDecimal(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        double global::System.IConvertible.ToDouble(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToDouble(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        short global::System.IConvertible.ToInt16(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToInt16(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        int global::System.IConvertible.ToInt32(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToInt32(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        long global::System.IConvertible.ToInt64(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToInt64(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        sbyte global::System.IConvertible.ToSByte(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToSByte(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        float global::System.IConvertible.ToSingle(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToSingle(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        string global::System.IConvertible.ToString(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToString(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        object global::System.IConvertible.ToType(global::System.Type conversionType, global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToType(conversionType, provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        ushort global::System.IConvertible.ToUInt16(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToUInt16(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        uint global::System.IConvertible.ToUInt32(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToUInt32(provider);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SuperStrong.Types.CodeAnalysis.Generators", "1.0.0.0")]
        ulong global::System.IConvertible.ToUInt64(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToUInt64(provider);
        }
    }

}
