//HintName: Sample_TestStrongType.g.cs
// <auto-generated />
#nullable enable

namespace Sample
{
    partial class TestStrongType : global::SuperStrong.Types.IStrongType<TestStrongType, int>
    {
        private readonly int _value;

        private TestStrongType(int value)
        {
            _value = value;
        }

        public static TestStrongType Create(int value)
        {
            global::SuperStrong.Types.StrongType.EnsureValid(value, Definition);

            return new TestStrongType(value);
        }

        public int AsPrimitive() => _value;
    }

    partial class TestStrongType : global::SuperStrong.Types.IHasStrongTypeDefinition<int>
    {
        public static global::SuperStrong.Types.StrongTypeDefinition<int> Definition { get; } = global::SuperStrong.Types.StrongType.GetTemplateDefinition<global::Sample.TestTemplate, int>();

        static global::SuperStrong.Types.StrongTypeDefinition<int> global::SuperStrong.Types.IHasStrongTypeDefinition<int>.Definition => Definition;
    }

    partial class TestStrongType : global::System.IEquatable<TestStrongType>, global::System.Numerics.IEqualityOperators<TestStrongType, TestStrongType, bool>
    {
        public bool Equals(TestStrongType? other) => other is not null && _value.Equals(other._value);

        public override bool Equals(object? obj) => obj is TestStrongType other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(TestStrongType? left, TestStrongType? right)
        {
            if (left is null)
            {
                return right is null;
            }

            return left.Equals(right);
        }

        public static bool operator !=(TestStrongType? left, TestStrongType? right) => !(left == right);
    }

    partial class TestStrongType
    {
        public override string ToString() => _value.ToString();
    }

    partial class TestStrongType : global::System.IParsable<TestStrongType>
    {
        public static TestStrongType Parse(string s, global::System.IFormatProvider? provider)
        {
            return Create(InvokeParse<int>(s, provider));

            static T InvokeParse<T>(string s, global::System.IFormatProvider? provider) where T : global::System.IParsable<T>
            {
                return T.Parse(s, provider);
            }
        }

        public static bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] string? s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            if (InvokeTryParse<int>(s, provider, out var primitive) && global::SuperStrong.Types.StrongType.IsValid(primitive, Definition))
            {
                result = new TestStrongType(primitive);
                return true;
            }

            result = null;
            return false;

            static bool InvokeTryParse<T>(string? s, global::System.IFormatProvider? provider, out T result) where T : global::System.IParsable<T>
            {
                return T.TryParse(s, provider, out result!);
            }
        }
    }

}
