namespace SuperStrong.Types.CodeAnalysis.Generators;

internal static class EmbeddedSources
{
    public const string StrongTypeAttributesHintName = "StrongTypeAttributes.g.cs";

    public const string StrongTypeAttributes = """
        // <auto-generated />
        #nullable enable

        namespace SuperStrong.Types
        {
            [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            internal sealed class StrongTypeAttribute<TPrimitive> : global::System.Attribute
                where TPrimitive : notnull;

            [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            internal sealed class StrongTypeAttribute<TPrimitive, TTemplate> : global::System.Attribute
                where TPrimitive : notnull
                where TTemplate : notnull, global::SuperStrong.Types.IStrongTypeTemplate<TPrimitive>;
        }
        """;
}
