using SuperStrong.Types.CodeAnalysis.Generators.FeatureEmitters;
using SuperStrong.Types.CodeAnalysis.Generators.Helpers;
using SuperStrong.Types.CodeAnalysis.Generators.Models;
using System.Collections.Immutable;
using System.Text;

namespace SuperStrong.Types.CodeAnalysis.Generators;

internal static class SourceBuilder
{
    public static string Build(StrongTypeModel model, ImmutableArray<IStrongTypeFeatureEmitter> features)
    {
        var writer = new IndentedWriter(new StringBuilder());

        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line();

        IDisposable? namespaceScope = null;

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            namespaceScope = writer.Block($"namespace {model.Namespace}");
        }

        var ancestorScopes = new Stack<IDisposable>();

        foreach (var ancestor in model.Ancestors)
        {
            ancestorScopes.Push(writer.Block($"partial {ancestor.Keyword} {ancestor.Name}"));
        }
        
        foreach (var feature in features)
        {
            feature.Emit(writer, model);
            writer.Line();
        }

        while (ancestorScopes.Count > 0)
        {
            ancestorScopes.Pop().Dispose();
        }

        namespaceScope?.Dispose();

        return writer.ToString();
    }
}
