//HintName: Sample_TestStrongType.g.cs
// <auto-generated />
#nullable enable

namespace Sample
{
    partial class TestStrongType : global::SuperStrong.Types.IStrongType<TestStrongType, int>
    {
        private readonly int _value;

        private TestStrongType(int value)
        {
            _value = value;
        }

        public static TestStrongType Create(int value)
        {
            global::SuperStrong.Types.StrongType.EnsureValid(value, Definition);

            return new TestStrongType(value);
        }

        public static bool TryCreate(int value, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute(false)] out TestStrongType result)
        {
            if (global::SuperStrong.Types.StrongType.IsValid(value, Definition))
            {
                result = new TestStrongType(value);
                return true;
            }

            result = null;
            return false;
        }

        public int AsPrimitive() => _value;

        int global::SuperStrong.Types.IStrongType<TestStrongType, int>.AsPrimitive()
        {
            return AsPrimitive();
        }
    }

    partial class TestStrongType : global::SuperStrong.Types.IHasStrongTypeDefinition<int>
    {
        public static global::SuperStrong.Types.StrongTypeDefinition<int> Definition { get; } = global::SuperStrong.Types.StrongType.Define<int>();

        static global::SuperStrong.Types.StrongTypeDefinition<int> global::SuperStrong.Types.IHasStrongTypeDefinition<int>.Definition => Definition;
    }

    partial class TestStrongType : global::System.IEquatable<TestStrongType>, global::System.Numerics.IEqualityOperators<TestStrongType, TestStrongType, bool>
    {
        public bool Equals(TestStrongType? other) => other is not null && _value.Equals(other._value);

        bool global::System.IEquatable<TestStrongType>.Equals(TestStrongType? other)
        {
            return Equals(other);
        }

        public override bool Equals(object? obj) => obj is TestStrongType other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(TestStrongType? left, TestStrongType? right)
        {
            if (left is null)
            {
                return right is null;
            }

            return left.Equals(right);
        }

        public static bool operator !=(TestStrongType? left, TestStrongType? right) => !(left == right);
    }

    partial class TestStrongType
    {
        public override string ToString() => _value.ToString();
    }

    partial class TestStrongType : global::System.IConvertible
    {
        global::System.TypeCode global::System.IConvertible.GetTypeCode()
        {
            return ((global::System.IConvertible)_value).GetTypeCode();
        }

        bool global::System.IConvertible.ToBoolean(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToBoolean(provider);
        }

        byte global::System.IConvertible.ToByte(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToByte(provider);
        }

        char global::System.IConvertible.ToChar(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToChar(provider);
        }

        global::System.DateTime global::System.IConvertible.ToDateTime(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToDateTime(provider);
        }

        decimal global::System.IConvertible.ToDecimal(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToDecimal(provider);
        }

        double global::System.IConvertible.ToDouble(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToDouble(provider);
        }

        short global::System.IConvertible.ToInt16(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToInt16(provider);
        }

        int global::System.IConvertible.ToInt32(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToInt32(provider);
        }

        long global::System.IConvertible.ToInt64(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToInt64(provider);
        }

        sbyte global::System.IConvertible.ToSByte(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToSByte(provider);
        }

        float global::System.IConvertible.ToSingle(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToSingle(provider);
        }

        string global::System.IConvertible.ToString(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToString(provider);
        }

        object global::System.IConvertible.ToType(global::System.Type conversionType, global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToType(conversionType, provider);
        }

        ushort global::System.IConvertible.ToUInt16(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToUInt16(provider);
        }

        uint global::System.IConvertible.ToUInt32(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToUInt32(provider);
        }

        ulong global::System.IConvertible.ToUInt64(global::System.IFormatProvider? provider)
        {
            return ((global::System.IConvertible)_value).ToUInt64(provider);
        }
    }

}
